# Generated by Django 5.2.15 on 2026-06-14 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lesson__course', 'lesson__order'],
                'indexes': [models.Index(fields=['student', 'lesson'], name='courses_les_student_e118e2_idx'), models.Index(fields=['completed'], name='courses_les_complet_d92e22_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_lesson_progress')],
            },
        ),
    ]
